backend:
  name: git-gateway
  branch: main

identity_url: https://praxis-website.netlify.app/.netlify/identity

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Seiten"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }